import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/ui/theme-provider"
import SideNavbar from './Components/SideNavbar'
import { Suspense } from 'react'
import Loading from './About/loading'
import Reveal from '@/components/Reveal'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-2  py-4`} >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <SideNavbar/>
            <Suspense fallback={<Loading/>}>
              <div className='pl-[1%] sm:pl-[4%] pr-[10%] sm:pr-[6%]'>
                {children}
              </div>
            </Suspense>
        </ThemeProvider>
      </body>
    </html>
  )
}
